### PR TITLE
override error handler in nokogiri parser

### PR DESCRIPTION
**Pull request by adjam**
Fixes ruby-marc/ruby-marc#55

Parsing will fail with a `StandardError` when processing bad XML with `nokogiri`.

### CODE REVIEW

**Comment by jrochkind** [comment]
Would this change be a backwards incompat, do you think? Or shall we consider it a bugfix? Either way, should it be configurable in case someone wants the old behavior?

Just asking questions, I'm not sure. 

I'm not sure who if anyone is really stewarding ruby-marc these days. @adjam , are you interested in commit/release privs?

Also not sure why travis is failing, let's see.... hmm, only on 1.9.3, looks becuase you can't use current version of rubygems-update to update rubygems on 1.9.3. :(  

~~~
Updating rubygems-update
ERROR:  Error installing rubygems-update:
	rubygems-update requires Ruby version >= 2.3.0.
ERROR:  While executing gem ... (NoMethodError)
    undefined method `version' for nil:NilClass
The command "gem update --system" failed and exited with 1 during 
```

Hypothetically there's an older version of rubygems-update we could get to work somehow. 

It may be time to drop 1.9.3 support... but I think that also requires a major version bump in my opinion. We could just release a 2.0?    Not sure who else there is to give an opinion, so I welcome yours @adjam .

**Comment by jrochkind** [comment]
This also ideally needs a test that error is raised when expected. 

I wonder if we should use a custom error subclass instead of a raw `StandardError`. Probably, for those who want to rescue it, which some will want to do -- including in the traject use case that led to this fix, some will want to rescue the error so subsequent records can still be processed. a custom error class will make that a lot more reliable.

**Comment by adjam** [comment]
I noticed the failing test, but figured that was more infrastructural.  Also, there are no travis configs for MRI IIUC.

When processing MARCXML with ruby-marc/Nokogri/libxml2 right now, is that anything that triggers the `error` brings the parsing to a halt -- under the covers, `libxml2` has given up, there is no recovery option.

The only indication one has that this has happened is checking `#errors` on the `NokogiriParser` instance after the last record has been `yield`ed -- doable, but that made me feel ooky.

Things might be different if you're using JRuby and whatever implementation of XML parsing Nokogiri uses.  Assuming it's some implementation of the SAXParser, then the ErrorHandler class defined by that API distinguishes between warnings, errors, and fatal errors [http://www.saxproject.org/apidoc/org/xml/sax/ErrorHandler.html).  IIRC, and the documtation suggests this without saying it outright, 'error' means *validation error* (well formed, but not schema compliant) while fatalError means "not well formed'.  The Nokogiri API does not appear to make this distinction, which suggests to me error => unrecoverable.

Wheels within wheels.

**Comment by jrochkind** [comment]
Yes, the travis failure is infrastructural, but we still gotta figure out what to do with it. 

Either get travis working on 1.9.3, or officially remove 1.9.3 support I think are the options. I think the latter probably requires a new ruby-marc major version. 

It's not your responsibility for this PR cause it has nothing to do with this... but there's not really anyone stewarding ruby-marc right now I don't think, so I could use the help. 

I can maybe work on the infrastructural though if you can give me advice and work on this one. 

For this one:

* You've convinced me it's a bugfix not a backward incompat.  :) Sounds like nothing useful was happening except the whole record being skipped in current code, it's not like the rest of the record was processable or anything?
* I think it needs a custom error class, not just StandardError. Not really sure if it should be a nokogiri-parser-specific one... probably just a general ruby marc one?
* It needs a test, just that if you give it bad XML, it raises the exception. I guess you _could_ just provide a test for the nokogiri parser, since that's what you're fixing. Although if you know rexml already raises too... maybe that should be tested too? And then _ideally_ it would raise the _same_ exception as nokogiri... but now _that_ might be a backwards incompat, to change what exception rexml raises. :(

Wheels within wheels indeed. 

I'm not sure if there's anyone else watching this repo to give us advice and feedback... @billdueber ? Anyone?

**Comment by adjam** [comment]
Oh, scratch that, there are MRI builds.  I'd suggest adding 2.4 and 2.5 in, if 1.9.3 gets dropped.  `nokogiri` pulls in its own patched versions of `libxml2` and `libxslt`, so I think maybe most of the yak shaving I thought might be needed above is already handled.

**Comment by jrochkind** [comment]
yes, we should def add testing in 2.4 and 2.5, regardless of whether we drop 1.9.3.

**Comment by adjam** [comment]
I tend to live closer to the edge, so I have no brief for retaining 1.9.3.  Agree that it's a major version bump to do so.  From my perspective -- and this is a guess -- the major downstream client is probably `traject` and you know its community better than I do.  No current versions of traject would be impacted, and you could do a version bump when you decide to incorporate ruby-marc 2.x

**Comment by jrochkind** [comment]
Ah, that made me think of a good point, traject has a dependency on marc 1.x, so couldn't use a 2.0 release without a new traject release. 

At one point, _lots_ of people used ruby-marc. It had a very long career before traject even came along. It may still be used by lots of people we don't hear from, and as such a "basic" lowish-level gem for the library industry... I'm loathe to drop 1.9.3 without at least a major version bump, since there may be passes of people using it, including on old out-of-support ruby versions. 

I think we can probably get travis to run on 1.9.3 again though. I'll try to find time to look into that, if you take care of this PR. :)

**Comment by jrochkind** [comment]
@adjam okay fixed in #57, if you rebase or merge master, you should get green, plus travis testing on 2.4 and 2.5.

**Comment by adjam** [comment]
Sigh: https://github.com/sparklemotion/nokogiri/issues/1847

**Comment by jrochkind** [comment]
Thank you for your work on this @adjam , appreciate it!

**Comment by adjam** [comment]
@jrochkind disabled the test on jruby, and everything passes (and the omit message references the nokogiri issue I opened) so it should be good to go, let me know if you want me to rebase.

**Comment by jrochkind** [comment]
Apparently you already did rebase to get the new travis, so that's good enough, I don't care about pristine commit history. 

I'd like to give it a week, or at this point until after the new year, to see if nokogiri will address the bug -- cause once we merge this, we're gonna forget to ever go back and put the test back in heh. Is that cool?

(Although nice job linking to the nokogiri issue, thanks!)

I'm also going to go ahead and add you as a committer/release privs for this repo as your "reward" haha. I don't think anyone else is currently really watching this repo.

**Comment by danschmidt5189** [comment]
@jrochkind FWIW a few of us at UC Berkeley (me, @helliger, some others) do watch/use ruby-marc.

Obviously this _does_ break backwards compatibility, at least technically — regardless of what the user's reasonable expectations are, the actual contract is going from "fail silently" to "raise". I'm still +1 on the change — I'd rather know about these errors than not know, and the BC alternative (making the error handler configurable) seems to add unnecessary complexity.

**Comment by adjam** [comment]
@danschmidt5189 glad to have more input!  Are you arguing for a major version number bump if this is merged?  In the thread on #55 -- and I might be wrong about this -- I noted that it brings the behavior of the XML parser *when Nokogiri is used* in line with what happens when the REXML parser is used, so what the "API" promises is at best unclear.

I would argue it's an implicit contract of just about any parser that it won't fail silently on syntax errors unless you go out of your way to ask it to.

I *think* I may have a fix ready for upstream Nokogiri, but that change is clearly a bug fix (brings the actual behavior in line with the documented API).  So, to incorporate this wholesale into ruby-marc would involve adding a dependency on a newer version of that gem.

All that said, does 1.1 sound right for a new version number?

**Comment by adjam** [comment]
Nokogiri accepted the PR enabling the error handler under jruby, once they've released 1.11.0 I'll update the test to only skip when running on an older version, and at that point I think we can call this done.

**Comment by danschmidt5189** [comment]
Hm… On reflection I think it's fair to call this a backwards-compatible bugfix. No one would knowingly write to the contract "fails silently on errors" given that the expected behavior (implemented by the other parsers) is to raise. 👍

Given that, [semver](https://semver.org) calls for bumping the patch version — v1.0.2 to v1.0.3.

**Comment by adjam** [comment]
OK, with the release of Nokogiri 1.10.2, XML parsing under JRuby should be on par with behavior under MRI (https://github.com/sparklemotion/nokogiri/releases/tag/v1.10.2).  I've updated the XML error handling test to run under JRuby when Nokogiri version >= `1.10.2`

I've updated the README to make a note of this, as it is slightly tricky behavior.

**Comment by jrochkind** [comment]
seems awesome. Should I merge? Should we release? Should I make you a ruby-marc committer and gem owner so you can do all that @adjam ? Thanks!

**Comment by adjam** [comment]
@jrochkind your call on how you want to handle the mechanics; most other projects I'm a part of have the rule that they who create the PR must be different from they who merge, but if that's not how it's done 'round these parts I'm fine taking on the rest of the steps.  Is the standard practice to merge the PR to  master, bump the version, then do the releasey parts?

**Comment by jrochkind** [comment]
I don't think there are any official policies for who merges what. I think I may be the only committer paying attention to this repo right now. For starters, I am going to add you as a committer and a rubygems "owner" (so you can do releases).  Then you will have as much authority and responsibility as I have for figuring out the "right" way to do it, as far as I'm concerned. :)

**Comment by jrochkind** [comment]
@adjam I need an email address you have as a rubygems.org account, so I can add you as a gem owner who can do releases. Not sure the best way to get that to me?

**Pull request merged**
