### PR TITLE
Pathname properly handled by MARC::Writer.new()

### PR DESCRIPTION
**Pull request by aseroff**
MARC::Writer.new() silently fails when passed a Pathname object to file.

**Description:** Significant behavior difference between providing a String and a Pathname to MARC::Writer.new. When provided a string, MARC::Writer.write properly adds the record to the file. When provided a Pathname, the MARC::Writer.write overwrites the file's contents, based on the fact that Pathname responds to 'write' (writer.rb line 35).

**Versions:** 
marc 1.0.4
Ruby 2.5.1

**Works:**
```
path = File.join(Rails.root, 'dir', 'file.mrc')
path.class
>> String
writer = MARC::Writer.new(path)
>> #<MARC::Writer:0x00007fb458273be8 @fh=#<File:/Users/aseroff/Repos/app/dir/file.mrc>, @allow_oversized=false>  
marc_records.each {|record| writer.write(record)}
writer.close
# Results in a marc file with each record included
```

**Silently fails until attempt to close writer:**
```
path = Rails.root.join('dir', 'file.mrc')
path.class
>> Pathname
writer = MARC::Writer.new(path)
>> #<MARC::Writer:0x00007fb4543e1b00 @fh=#<Pathname:/Users/aseroff/Repos/app/dir/file.mrc>, @allow_oversized=false>
marc_records.each {|record| writer.write(record)}
writer.close
>> NoMethodError (undefined method `close' for #<Pathname:/Users/aseroff/Repos/app/dir/file.mrc>)
# dir/file.mrc contains last record only (overwrites file on each write)
```

**Current Workaround:**
```
MARC::Writer.new(Rails.root.join('dir', 'file.mrc').to_s)
```

**Provided Solution**: Opens file at pathname (mimics behavior of when String is provided)

### CODE REVIEW

**Comment by adjam** [comment]
@aseroff thanks for the issue report!

I'm not sure that I'd want to merge the PR as-is, for a few reasons.

First, this seems like an API change (which would require a major version upgrade) to support a slightly unusual usage; even though it's part of the standard library, you have to `require 'pathname'` in order to use it, which already suggests you've gone out of your way.  So if you want to trade in `Pathname` objects, that's fine, but you always have the option of calling `File.open(pathname, 'w')` yourself, or calling `to_s`.

Sorry if this sounds a bit unfair -- you've gone to the trouble of using a class that makes working with pathnames more predictable, and you're being forced to do more work than code that doesn't make use of that.  This is, in part, a reflection of the age of this gem (IIUC, it predates `Pathname`).

We can perhaps blame the semantics of `Pathname#write` here since they seem destined to create a bit of confusion when using duck-typing.

Second, the patch itself would cause instantiation to fail when the user provides an `IO` object and hasn't themselves called `require 'pathname'` (which this gem does not yet do); i.e. at the point it checks to see whether the object is a `Pathname`, it hasn't seen that constant yet:

```ruby 
def handle(thing)
  if thing.is_a?(String) || thing.is_a?(Pathname)
    File.open(thing, 'w')
  elsif thing.respond_to?(:write)
    thing
  end
end

handle(File.open("/dev/null", 'w'))

```

(paste that into an `irb` session, e.g.)

Third (and this should probably be noted in a contributor's guide), all PRs should be accompanied by unit tests for the new functionality.

I am not opposed to baking in support for `Pathname`s in the API at some point in the future, but for the API-changing considerations alone, that seems like the sort of thing to be considered for a 2.0 release.

**Comment by aseroff** [comment]
That all seems entirely reasonable. Originally I was writing an Issue for my bug, but then decided to take a stab at fixing the issue myself. Perhaps this PR will get fleshed out and folded into an update with some other features, perhaps it will just serve as a pointer to help someone who gets stuck when the gem behaves unexpectedly for them.

Thanks for your thoughtful response and your work on this gem.

**Comment by jrochkind** [comment]
I don't think it actually predates Pathname, which is in ruby core. 

If you're using Rails, you already have `Pathname` required for you. Or if you're using lots of other things. Ruby patterns for whether something from core is required or not are a bit weird, if *any* dependency "required" it, it's already there. 

So I think it could be okay for ruby-marc to just `require 'pathname'` so that it can check to see if something is one. 

And the code is already testing for special handling for String, I think checking for special handling for Pathname *could* be justified. 

But I don't feel strongly, and I appreciate @adjam's work to maintain ruby-marc -- we've been kind of short on maintainer resources. So I think it could also be justified to say we won't add convenience features like this, cause we're just trying to keep our maintenance burden from growing. 

I think it's defensible to merge it though, it's pretty simple -- I'd lean toward adding it myself, but don't feel strongly. It would need tests to be merged though!

**Comment by jrochkind** [comment]
PS: If you know you have a pathname, just passing in `the_pathname.to_s` instead of `the_pathname` should get ruby-marc to do what you want.

**Comment by adjam** [comment]
@jrochkind thanks for providing some more context.  If you're +1 on merging it, I can live with that.

@aseroff one thing I didn't mention -- you should prefer `is_a?` to `.class ==` when checking things in the constructor.

My primary worry is that it's skulking around the neighborhood of an API change if it isn't one.  I'll stick with pinning the primary blame on the semantics of `Pathname#write` being out of step with what `#write` usually means.  I guess it won't change behavior for anybody using strings or io objects though, so it's backward compatible.

I'll get around to drafting up some contributor guidelines which, should you have the time, we can discuss.

I'm relatively new to the Ruby game, so I'd seen what I thought was some evidence `Pathname` was added 1.9ishly, which appears not to be the case.  There is still an open issue on this repo about support for 1.8!  (not having been around for that conversation, I haven't tried to close it).

**Comment by adjam** [comment]
@aseroff thanks!

**Comment by jrochkind** [comment]
I *think* Pathname predates 1.9, but 1.9 is ancient at this point anyway, doesn't really matter either way. 

The existing String test used `==`, but good catch! is_a? (or `kind_of?` which I think is a synonym) is better for allowing sub-classes too. 

But then should String be chagned too? I think so?

In general, I'm not worried about backwards compat, it didn't do anything useful with Pathname before (or, I guess with a sub-class of String if you somehow had one!), so we aren't possibly breaking anything that worked before.

**Comment by aseroff** [comment]
Let me know if there's anything else I can do here. Thanks again for the review.

**Comment by aseroff** [comment]
I am starting to wonder if this PR is unnecessary. My thought process was: if this really is a convenience feature for Pathname.to_s, perhaps a better way would be to have Pathname inherit String. 

Well, no need, because Pathname includes File functionality. So it's probably better if the client just passes the opened io object with `MARC::Writer.new(pathname.open('w))` like your original response suggested. 

So really, this issue is just a safety net for people who make the same mistakes I did with Pathname objects, and isn't really a problem for this gem to be addressing. If anything, perhaps the better change would be just additional documentation.

```
# writing a record
writer = MARC::Writer.new('marc.dat') # or
writer = MARC::Writer.new(Pathname.new('dir', 'marc,dat').open('w'))
```

**Comment by jrochkind** [comment]
That makes sense to me. The gem can't save people from all mistakes (or even document all of them possible). 

>  if this really is a convenience feature for Pathname.to_s, perhaps a better way would be to have Pathname inherit String.

Of course, that would be up to ruby core, not us, and the decision has already been made by them. :)

**Comment by adjam** [comment]
Overall, it seems like an improvement.  Not a big enough improvement all by itself to merit a new release, but   an improvement nonetheless =)

I'm struck by the fact that this hasn't been reported as an issue up to this point, and I'm willing to make a really really small bet that `Pathname` isn't very widely used in this sort of context in part because its API puts it at odds with duck-typing in Ruby (`Pathname#write` doesn't quack, it honks).  IMO, it's a weird class/module:

```
All functionality from File, FileTest, and some from Dir and FileUtils is included, in an unsurprising way. It is essentially a facade for all of these, and more.
```

**Comment by billdueber** [comment]
I'm revisiting this as I go through PRs. I love me some `Pathname` so I'd like to make it work. And it's worth revisiting our error reporting anyway.

Attempts to find non-classname-based differentiating factors failed:

* Like `File`, `Pathname.responds_to?` `:read`, `:write`, and `:to_path`
* `Pathname` is _not_ `kind_of? IO`, but neither is `StringIO`.  
* `File.new` will take a `File`, `IO`, `String`, or `Pathname`, but not a `StringIO`, and we don't want to be calling `File.new(open_file_handle)` anyway because it doesn't allow you to pass in already_written_to files. 
* `Pathname.new` will take anything that implements `to_str` which includes files as well as Strings and other Pathanmes

So, I think I arrived where everyone else seems to have already been: `Pathname` just has to be special-cased. 

I'm proposing something like the following:

```ruby
require 'pathname'

# writer
if f.kind_of? String or f.kind_of? Pathname
  @handle = File.open(f)
elsif f.respond_to(:write)
  @handle = f
else 
  raise ArgumentError, "Can't interpret '#{f.inspect}' as a file to write. Expect an IO/File object, String with the filename, or Pathname object"
end

# readers
if f.kind_of? String or f.kind_of? Pathname
  raise ArgumentError, "'#{self.class} can't read file #{f}" unless Pathname.new(f).readable?
  @handle = File.open(f)
elsif f.respond_to(:read, 5)
  @handle = f
  # really can't do any sort of checking here; IO/File/StringIO objects are all edge cases
else 
  raise ArgumentError, "Can't interpret '#{f.inspect}' as a file to read. Expect an IO/File object, String with the filename, or Pathname object"
end

```

This is substantially what @aseroff already did, but with longer error messages and checks.

Any thoughts?

**Comment by billdueber** [comment]
I'm back to thinking this is just more trouble than it's worth. Users will get a clean failure with error message when they use a pathname instead of a string and it's an easy fix. I'm gonna close this without merging, but want to than @aseroff for the work you've put in.

**Pull request closed without merging**
