### PR TITLE
Prevent NoMethodError when comparing objects of different types

### LINKED ISSUE #80: Equals methods for ControlField, DataField, and Subfield are not compatible with other types
I ran into this in a unit test for a [MARCSpec implementation I'm working on](https://github.com/dmolesUC/marc_spec), where the expected value was a Subfield object, but the actual value was a string — instead of an equality check failure, I got a NoMethodError.

## Steps to reproduce

- Compare a ControlField, DataField, or Subfield to an object of a different type, e.g.:

  1. `MARC::ControlField.new('001', 'foobarbaz') == '001'`
  2. `MARC::DataField.new('100') == '100'`
  3. `MARC::Subfield.new('a', 'foo') == 'foo'`

## Expected

- All three statements evaluate to `false`

## Actual

- All three statements raise `NoMethodError`:

   1. 
     ```none
     NoMethodError: undefined method `code' for "foo":String
     Did you mean?  encode
     /Users/david/Work/Scratch/ruby-marc/lib/marc/subfield.rb:19:in `=='
     ```

   2. 
     ```none
     NoMethodError: undefined method `tag' for "100":String
     Did you mean?  tap
     /Users/david/Work/Scratch/ruby-marc/lib/marc/datafield.rb:168:in `=='
     ```

   3. 
     ```none
     NoMethodError: undefined method `tag' for "001":String
     Did you mean?  tap
     /Users/david/Work/Scratch/ruby-marc/lib/marc/controlfield.rb:56:in `=='
     ```

## Notes

The simplest fix would be to insert an `is_a?` check at the start of each `==` implementation, and I have a PR I'll submit, but you could also do something elaborate like `[<accessor1>, <accessor2>...].all? { |acc| other.respond_to?(acc) }`.

### PR DESCRIPTION
**Pull request by dmolesUC**
Fixes #80.

### CODE REVIEW

**Comment by billdueber** [comment]
You're right of course -- I've apparently had that wrong in my head for years now.

**Comment by jrochkind** [comment]
@billdueber It looks like this merge may have broken the PR build, on jruby.  

Or master branch may have been broken already, just not tested regularly. 

I'm not sure why the CI results don't show up on this PR though, it may not be set up properly?

In any event, it looks like master may currently be failing the build on jruby.

**Comment by billdueber** [comment]
Well crap. I'll take a look at the code and the CI

**Comment by dmolesUC** [comment]
@jrochkind sorry to hear it. @billdueber if it isn't something obvious, let me know and I'll have a go at setting up JRuby.

**Comment by dmolesUC** [comment]
@billdueber See [my comment](https://github.com/ruby-marc/ruby-marc/issues/86#issuecomment-1028210986) on @jrochkind's #86.

**Pull request merged**
